version: '3'

services:
  refresh:
    build:
      context: .
    image:
      build-docker-mid-server:latest
    container_name:  
      refresh
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - .env
    restart: always
    