version: '3'

services:
  node:
    build:
      context: .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      HOST: 
      USER_NAME: 
      PASSWORD: 
      PROXY: 
      PROXY_PORT: 
      SN_HOST_NAME:
    